name: Node CI

on:
  - push
  - pull_request

env:
  SESSION_KEY: ${{ secrets.SESSION_KEY }}
  ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          cache: 'npm'
      - run: make setup
      - run: make lint
      - run: make test
